version: '3.8'
services:
  dynamodb-loc:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-loc
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  #   app-node:
  #     working_dir: /home/node/app
  #     depends_on:
  #       - dynamodb-loc
  #     image: "node:16-alpine"
  #     container_name: app-node
  #     ports:
  #       # - "8080:8080"
  #       - "3000:3000"
  #     volumes:
  #       - ./:/home/node/app
  #       - ./docker/root:/root
  #     command: "npm run dev"
  #     networks:
  #       - my_network

  # networks:
  #   my_network:
  #     driver: bridge
  # app-node-backend:
  #   working_dir: /home/node/app
  #   depends_on:
  #     - dynamodb-loc
  #   image: "node:16-alpine"
  #   container_name: app-node-backend
  #   ports:
  #     - "8080:8080"
  #     # - "3000:3000"
  #   volumes:
  #     - ./:/home/node/app
  #     - ./docker/root:/root
  #   command: "npm run start:dev"
